### ISSUE TITLE
cloud-agnostic/generic type for instance types

### ISSUE THREAD

**Issue by imaskm** [netbookai/spawner#17]
**Is your feature request related to a problem? Please describe.**
As a user, one shouldn't need to remember or keep track of the different instance types of all the clouds I am using, there should be a generic nomenclature which should be easy to remember and should be cloud independent.

**Describe the solution you'd like**
Terraform uses a generic nomenclature for instance types, here is the list with respective cloud instance types:
[ Terraform instance types](https://registry.terraform.io/providers/iterative/iterative/latest/docs/guides/generic-machine-types)

**Describe alternatives you've considered**

**Additional context**

**Comment by NishanthSpShetty** [comment]
this is really good. I think we can achieve this by allowing spawner take machine_type as optional field along with instance type.

As spawner is used along with other orchestration service, we would want to keep exisitng instance type as it provides more fine grained control over the instance we spawn across different cloud,

**Comment by NishanthSpShetty** [comment]
added support for the requested feature. https://github.com/NetBook-ai/spawner/pull/16
Now you can specify machine type in request.
```{
    "nodeSpec": {
        "diskSize": 31,
        "name": "prosint-1-micro",
        "count": 3,
        "machineType": "m",
        "instance":"t2.micro",
        "labels": {
            "created_by": "cli"
        }
    },
    "region": "us-east-2",
    "clusterName": "my-cluster",
    "provider": "aws"
}
```
